### ISSUE TITLE
Implement all direct upload events

### ISSUE THREAD

**Issue by safeforge** [algonauti/ember-active-storage#16]
Full list of events are available at https://github.com/rails/rails/tree/master/activestorage#direct-upload-javascript-events

**Comment by shaunwillis-SpectrumReach** [comment]
request was formatted incorrectly....
<img width="1292" alt="screen shot 2018-09-04 at 12 39 42 pm" src="https://user-images.githubusercontent.com/33098739/45047790-af94e880-b03f-11e8-80f8-e64ab592ed76.png">
<img width="563" alt="screen shot 2018-09-04 at 10 27 19 am" src="https://user-images.githubusercontent.com/33098739/45047799-b4599c80-b03f-11e8-89c6-93eca05a88bb.png">

getting this error in ember.... send this to a rails api-only environment...

any help is appreciated.
