### ISSUE TITLE
the required parameter, data, is missing

### ISSUE THREAD

**Issue by shaunwillis-SpectrumReach** [algonauti/ember-active-storage#19]
@safeforge 

getting this error

request was formatted incorrectly....
<img width="1292" alt="screen shot 2018-09-04 at 12 39 42 pm" src="https://user-images.githubusercontent.com/33098739/45047790-af94e880-b03f-11e8-80f8-e64ab592ed76.png">
<img width="563" alt="screen shot 2018-09-04 at 10 27 19 am" src="https://user-images.githubusercontent.com/33098739/45047799-b4599c80-b03f-11e8-89c6-93eca05a88bb.png">

<img width="991" alt="screen shot 2018-09-04 at 12 44 42 pm" src="https://user-images.githubusercontent.com/33098739/45048009-54172a80-b040-11e8-9e80-c71761dba41c.png">

getting this error in ember.... i'm sending this request from ember.js to a rails api-only environment...

any help is appreciated.

**Comment by safeforge** [comment]
@shaunwillis-SpectrumReach can you share a repository I can use to reproduce the bug?
