### ISSUE TITLE
NotFoundError when sending authentication headers 

### ISSUE THREAD

**Issue by belgoros** [algonauti/ember-active-storage#20]
I'm using ESA (**Ember-Simple-Auth**) with **Rails 5.2.0** backend API. I copy-pasted the code you [provided](https://github.com/algonauti/ember-active-storage#sending-authentication-headers) in `README`. Your [example app](https://github.com/algonauti/ember-active-storage-example) woks fine, but when using with headers where I need to pass in `Bearer <token value>` fails. I displayed the header values coming from `services/active-storage.js`:
```
export default ActiveStorage.extend({
  session: service(),

  headers: computed('session.isAuthenticated', function() {
    var headers = {};
    get(this, 'session').authorize('authorizer:application', (headerName, headerValue) => {
      console.log('++++++++++++ headerName: ' + headerName +', headerValue: ' + headerValue);
      headers[headerName] = headerValue;
    });
    return headers;
  })
});
```
and the values are correct:
```
++++++++++++ headerName: Authorization, headerValue: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ik1BSU4ifQ.eyJzY29wZSI6WyJwcm9maWxlIiwib3Blbm...
```
Here is screenshot of the error in the console:
<img width="358" alt="screenshot 2018-10-31 at 10 45 21" src="https://user-images.githubusercontent.com/83579/47779734-20801600-dcfa-11e8-9539-afe062a92d6f.png">

All my controllers in Rails are protected and expect to get a token from the header:
```
class ApplicationController < ActionController::API
...
before_action :authorize_request

private

  def authorize_request
    @current_user = (AuthorizeApiRequest.new(request.headers).call)[:user]
  end
```
Any idea ?  Or may be I'm missing something ? 
- may be it's just because I'm using Rails API and `direct_uploads_controller` is not available ?
- may be should we use a [Rails way](https://guides.rubyonrails.org/active_storage_overview.html#integrating-with-libraries-or-frameworks) to do that by using `DirectUpload` class ? Is it possible ?

Thank you !

**Comment by belgoros** [comment]
It seems that there is already a [PR](https://github.com/rails/rails/pull/32238) waiting to be merged.

**Comment by belgoros** [comment]
I have have pushed 2 example apps:
- [Rails API](https://github.com/belgoros/draft-api), see [add_file_upload](https://github.com/belgoros/draft-api/tree/add_file_upload) brach fr the latest commits (WIP)
- [Ember app](https://github.com/belgoros/draft-app), see [add_file_upload](https://github.com/belgoros/draft-app/tree/add_file_upload) for the latest commits (WIP).

Finally, the problem is in the URL to hit when displaying a Post photo in ember template:
```
{{#if post.photo}}
  <img src="{{post.photo}}" class="img-thumbnail" height="32" width="32">
{/if}}
```
In this case Ember tries to load the photo from `localhost:4200` host:
```
GET http://localhost:4200/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6209e9184fe8b05b5ce883ac1d38cfde6925c16b/JRuby_400x400.png 404 (Not Found)
```
instead of `localhost:3000`.

Thank you.

**Comment by belgoros** [comment]
I fixed the problem, you can take a look at the last modifications in [Rails API project](https://github.com/belgoros/draft-api) as well at [Ember app](https://github.com/belgoros/draft-app) that it uses.

**Comment by safeforge** [comment]
@belgoros are you using `ember s --proxy http://localhost:3000`?

**Comment by belgoros** [comment]
@safeforge No, I've set `aipHost` variable in `environment.js` as follows:
```
if (environment === 'development') {
    ENV.apiHost = 'http://localhost:3000';
    // ENV.APP.LOG_RESOLVER = true;
    // ENV.APP.LOG_ACTIVE_GENERATION = true;
    // ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    // ENV.APP.LOG_VIEW_LOOKUPS = true;
  }
..
if (environment === 'production') {
    ENV.apiHost = process.env.API_HOST;
  }
```
and then used it as follows in `application.js` adapter:
```
#adapters/application.js

import DS from 'ember-data';
import { pluralize } from 'ember-inflector';
import { underscore } from '@ember/string';
import config from '../config/environment';

export default DS.JSONAPIAdapter.extend({
  host: config.apiHost,

  pathForType: function(type) {
    let underscored = underscore(type);
    return pluralize(underscored);
  },
});
```

**Comment by safeforge** [comment]
@belgoros I'm pretty sure the code posted by you forwards only api requests. I suggest you to use `--proxy` in order to delivery all missing endpoints to the backend. e.g. `GET http://localhost:4200/rails/`

**Comment by belgoros** [comment]
@safeforge As far as I know passing in `--proxy` option overrides the backend url Ember should use for any backend request. The default one is `localhost:4200`. It means that every time when Ember code sees calls to `store.XXX` methods, it will use `host` value from the adapter if not take the one from `--proxy` option if provided, otherwise - use the default one (`localhost:4200`).

**Comment by safeforge** [comment]
@belgoros FYI `ember-active-storage` doesn’t use `ember-data`, you need to proxy requests to the backend in order to download the files. Currently, in all my ember projects I’m using the `--proxy` option

**Comment by belgoros** [comment]
@safeforge Yes, I know that, it is in [file-upload](https://github.com/belgoros/draft-app/blob/master/app/components/file-upload.js#L16) component. That's why to make it work in any environment, no matter you pass in `--proxy` option or not, I used `apiHost` variable defined in `environment.js` file. I also had to define [default url options](https://github.com/belgoros/draft-api/blob/master/config/environments/development.rb#L32) in the rails-api app. The aim of the opened issue was not to force for some modifications but just to get some attention and tell that may be it is worth to mention it in the add-on `README` file. Sure it's up to you.

**Comment by algodave** [comment]
@belgoros Please have a look at PR #22 and see if that addresses your original issue. Thanks!

**Comment by belgoros** [comment]
@algodave Thank you for the response. No, it is not the same. All my requests already contain the needed header values (authorization, bearer, etc.).  So I don't really need to do the steps described in [Sending authentication headers section](https://github.com/algonauti/ember-active-storage#sending-authentication-headers).

**Comment by algodave** [comment]
Ok @belgoros so, could you please check that your issue still occurs on the current master, and if so, please describe it again here? That because the conversation evolved in a way that it's now difficult to me understanding what's your issue. Thanks again!
