### ISSUE TITLE
Make jQuery optional

### ISSUE THREAD

**Issue by kpfefferle** [algonauti/ember-active-storage#21]
This addon assumes the presence of the ember-ajax addon which in turn assumes the presence of jQuery. Now that jQuery is optional in Ember itself, it would be nice if jQuery was also optional in this addon. Perhaps ember-active-storage might be updated to use ember-fetch or a similar non-jQuery approach?

**Comment by safeforge** [comment]
@kpfefferle seems a good idea. PR?

**Comment by kpfefferle** [comment]
When I looked into this deeper, I realized that ember-active-storage doesn't exercise a whole lot of features of XMLHttpRequest, so I wrote a direct implementation of XMLHttpRequest that covers only what this addon needs. The PR above removes the need for ember-ajax and jQuery without adding any other new dependency.
