### ISSUE TITLE
ActiveSupport::MessageVerifier::InvalidSignature when updating

### ISSUE THREAD

**Issue by belgoros** [algonauti/ember-active-storage#26]
I followed the [tutorial](https://www.algonauti.com/posts/powering-your-ember-apps-with-rails-active-storage), then forked the provided [example](https://github.com/algonauti/ember-active-storage-example) and [implemented](https://github.com/belgoros/ember-active-storage-example) `update` and `destroy` actions to be able to update and delete a company.
Unfortunately, it fails in case if you update an existing company without modifying its attached logo, just its name. Here is the error stack trace:
```
Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.6ms)
ActiveSupport::MessageVerifier::InvalidSignature (ActiveSupport::MessageVerifier::InvalidSignature):
```
Any idea on what is wrong with that? Or the `ember-active-storage` add-on **does not support** it? Thank you.

**Comment by belgoros** [comment]
But when changing the `CompanySerializer#logo` method to send a hash:
```
# company_serializer.rb

def logo
    if object.logo.attached?
      {
        url: rails_blob_url(object.logo),
        signed_id: object.logo.signed_id
      }
    end
  end
```
will solve the issue if you update the frontend code as follows:
```
#templates/companies/index.hbs, L:17

src={{company.logo.url}}
```
as well as here:
```
# templates/components/company-form.hbs, L:15

src={{company.logo.url}}
```
And you should have the following in `controllers/companies/edit.js` `update` action:
```
if (company.get('logo.signed_id')) {
  company.set('logo', company.get('logo.signed_id'));
}
```
It seems like Rails [creates a hidden input](https://guides.rubyonrails.org/active_storage_overview.html#direct-uploads) containing `signed_id` value. In your case, you set it only when attaching a new file in `companies/new.js` controller `setCompanyLogo(blob)` action.

What do you think? I haven't committed the above changes to `master` leaving the code as it is to reproduce the error.
I created a separate [branch](https://github.com/belgoros/ember-active-storage-example/tree/update_model_without_changing_image) containing the above modifications.

**Comment by sinankeskin** [comment]
Hi.

I'm %100 sure this is a server side issue. It has nothing with this addon.

@safeforge You can close confidently.

**Comment by safeforge** [comment]
@sinankeskin thanks for reminding me, this really went out of my radar. 💪
