### ISSUE TITLE
Import problems

### ISSUE THREAD

**Issue by fsmanuel** [algonauti/ember-active-storage#44]
Hey @safeforge 

The new version has the problem that you renamed the package and use the package name for the imports:
https://github.com/algonauti/ember-active-storage/blob/6c6b11e96a0e969998139050ac9de2ffd24a4b23/index.js#L4

Now the service import from the README does not work anymore. If I change the import the internal imports in `addon` do not work anymore.

I guess the easiest is to hardcode `ember-active-storage` in `index.js` or rename all the internal imports and change the readme.

**Comment by safeforge** [comment]
@fsmanuel thank you for report the bug! I just released a new patch version, please let me know any issue.

**Comment by fsmanuel** [comment]
@safeforge great. I'll test and let you know if I run into any problems.
You should also change the example in the README:

```
import ActiveStorage from 'ember-active-storage/services/active-storage';
```
with a hint on the 2.0 version to not frustrate new users.
